### ISSUE TITLE
The Example and HostingExample in Xcode can not compile

### ISSUE THREAD

**Issue by OneeMe** [OpenSwiftUIProject/OpenSwiftUI#160]
I encounter these errors when I try to run the Example and HostingExample:

Example:
<img width="1374" alt="image" src="https://github.com/user-attachments/assets/3ee1b829-dc79-4e3c-9d4c-0ff0fec9b094">

HostingExample:
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/5e6cc9b0-7ea7-4928-a27d-9469f14451bc">

Here, I think it's because when we build project in Xcode, there is no `OPENSWIFTUI_TARGET_RELEASE` specified, so the `platforms` of the OpenSwiftUI package fallback to the default iOS 18.0, but the App's min deployment target is iOS 15.0 and iOS 13.0.

Should we change the min target to the iOS 18.0 since they are only playground for the OpenSwiftUI.😆

**Comment by Kyle-Ye** [comment]
Yeah. The example can't be compile with dev/main branch.

You can try the example with 0.1.0 tag.

Changed a lot of implementation on the main branch and still working on the release of 0.2.0. I'll update the example project when it is ready.

**Comment by OneeMe** [comment]
OK, I got it. Is there any roadmap of 0.2.0? Maybe I can try to offer some code to it.

**Comment by Kyle-Ye** [comment]
In the near future. Complete a basic Color rendering it the goal.

**Comment by OneeMe** [comment]
You mean that OpenSwiftUI can render code like this correctly?

```swift
struct ColorBlocksView: View {
    var body: some View {
        VStack(spacing: 10) {
            Rectangle()
                .fill(Color.red)
                .frame(width: 100, height: 100)
            
            Rectangle()
                .fill(Color.green)
                .frame(width: 100, height: 100)
            
            Rectangle()
                .fill(Color.blue)
                .frame(width: 100, height: 100)
        }
    }
}
```

**Comment by Kyle-Ye** [comment]
Not now. The 0.2.0 should support such.
