### ISSUE TITLE
Example and HostingExample code can't be built in Xcode 15.3

### ISSUE THREAD

**Issue by bcbod2002** [OpenSwiftUIProject/OpenSwiftUI#82]
Hi Team,
I am trying to build the Example project in Xcode 15.3 and the simulator is 17.4
But I got a bunch of errors related to `Multiple commands produce xxxxxxx`
Is there any environment configuration that I set is wrong?

Here is the error message that I got, please check
<img width="654" alt="Screenshot 2024-04-23 at 23 14 15" src="https://github.com/OpenSwiftUIProject/OpenSwiftUI/assets/5748148/685f2374-5391-4143-b764-daaba3528216">

Thank you

**Comment by Kyle-Ye** [comment]
Have no problem with Xcode 15.3 + iOS 17.4

Please check `README.md` and `Example/README.md`. Have you checked out OpenGraph in the same directory of OpenSwiftUI?

**Comment by bcbod2002** [comment]
Hi Kyle, yes I have done that. OpenGraph and OpenSwiftUI are located in the same directory
GitHub
    |__OpenSwiftUI
    |__OpenGraph
<img width="1714" alt="Screenshot 2024-04-24 at 09 25 44" src="https://github.com/OpenSwiftUIProject/OpenSwiftUI/assets/5748148/5c291638-83b7-4888-a959-95df8c382b02">

**Comment by Kyle-Ye** [comment]
Close due to no further response.

You can reopen it with some more detailed information attached.
